//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigillo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sigillo.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm if the young person wish to consent for himself/herself..
        /// </summary>
        public static string AgeOfConsent_Confrimation {
            get {
                return ResourceManager.GetString("AgeOfConsent_Confrimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A young person under the age of 16 years may sign here if they have been shown to have capacity..
        /// </summary>
        public static string AgeOfConsent_Description {
            get {
                return ResourceManager.GetString("AgeOfConsent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age of Consent.
        /// </summary>
        public static string AgeOfConsent_Header {
            get {
                return ResourceManager.GetString("AgeOfConsent_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Procedures.
        /// </summary>
        public static string AlternativeProcedures_Title {
            get {
                return ResourceManager.GetString("AlternativeProcedures_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General and/or Regional Anaesthesia.
        /// </summary>
        public static string Anaesthesia_GeneralAnaesthesia {
            get {
                return ResourceManager.GetString("Anaesthesia_GeneralAnaesthesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Anaesthesia.
        /// </summary>
        public static string Anaesthesia_LocalAnaesthesia {
            get {
                return ResourceManager.GetString("Anaesthesia_LocalAnaesthesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Anaesthesia_Other {
            get {
                return ResourceManager.GetString("Anaesthesia_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedation.
        /// </summary>
        public static string Anaesthesia_Sedation {
            get {
                return ResourceManager.GetString("Anaesthesia_Sedation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anaesthesia.
        /// </summary>
        public static string Anaesthesia_Title {
            get {
                return ResourceManager.GetString("Anaesthesia_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I confirm that the decision made on behalf of the patient was reached after careful consideration of all the facts and the views expressed by those with an interest in the patient&apos;s welfare.  I consider the decision to be in the best interests of the patient and is the least restrictive option available..
        /// </summary>
        public static string AssentDecision_AssentDecisionConfirmation {
            get {
                return ResourceManager.GetString("AssentDecision_AssentDecisionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decision made, on the basis of all the facts and views expressed.
        /// </summary>
        public static string AssentDecision_AssentDecisionDescription {
            get {
                return ResourceManager.GetString("AssentDecision_AssentDecisionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Maker Signature.
        /// </summary>
        public static string AssentDecision_DecisionMakerSignature {
            get {
                return ResourceManager.GetString("AssentDecision_DecisionMakerSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Decision.
        /// </summary>
        public static string AssentDecision_FinalDecision {
            get {
                return ResourceManager.GetString("AssentDecision_FinalDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision.
        /// </summary>
        public static string AssentDecision_Header {
            get {
                return ResourceManager.GetString("AssentDecision_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details.
        /// </summary>
        public static string AssentDecision_InterestedPartiesContact {
            get {
                return ResourceManager.GetString("AssentDecision_InterestedPartiesContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AssentDecision_InterestedPartiesName {
            get {
                return ResourceManager.GetString("AssentDecision_InterestedPartiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string AssentDecision_InterestedPartiesRelationship {
            get {
                return ResourceManager.GetString("AssentDecision_InterestedPartiesRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string AssentDecision_InterestedPartiesView {
            get {
                return ResourceManager.GetString("AssentDecision_InterestedPartiesView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the decision relates to treatment, is there an advance decision in place? (Important in cases where life-sustaining treatment is being refused).
        /// </summary>
        public static string AssentDetails_AdvanceDecisionIsInPlace {
            get {
                return ResourceManager.GetString("AssentDetails_AdvanceDecisionIsInPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it necessary to consider issues around Deprivation of Liberty?.
        /// </summary>
        public static string AssentDetails_DOLSRequired {
            get {
                return ResourceManager.GetString("AssentDetails_DOLSRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assent.
        /// </summary>
        public static string AssentDetails_Header {
            get {
                return ResourceManager.GetString("AssentDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has an IMCA been instructed?.
        /// </summary>
        public static string AssentDetails_IMCAHasBeenInstructed {
            get {
                return ResourceManager.GetString("AssentDetails_IMCAHasBeenInstructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there anyone with lasting powers of attorney for welfare or a court deputy for making health decisions? (Note that some LPAs are for financial affairs only).
        /// </summary>
        public static string AssentDetails_LPAIsAvailable {
            get {
                return ResourceManager.GetString("AssentDetails_LPAIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are the patient&apos;s friends/family appropriate and willing to be consulted?.
        /// </summary>
        public static string AssentDetails_PatientFriendFamilyWillingToBeConsulted {
            get {
                return ResourceManager.GetString("AssentDetails_PatientFriendFamilyWillingToBeConsulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the patient expressed a view?.
        /// </summary>
        public static string AssentDetails_PatientHasExpressedAView {
            get {
                return ResourceManager.GetString("AssentDetails_PatientHasExpressedAView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does the patient have friends/family who can be consulted?.
        /// </summary>
        public static string AssentDetails_PatientHasFriendFamilyToConsult {
            get {
                return ResourceManager.GetString("AssentDetails_PatientHasFriendFamilyToConsult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assent Details.
        /// </summary>
        public static string AssentDetails_Title {
            get {
                return ResourceManager.GetString("AssentDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can the decision wait?.
        /// </summary>
        public static string CapacityDetails_CanTheDecisionWait {
            get {
                return ResourceManager.GetString("CapacityDetails_CanTheDecisionWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there an impairment of or disturbance in the functioning of the patient&apos;s mind or brain?.
        /// </summary>
        public static string CapacityDetails_DoesPatientHaveASoundedMind {
            get {
                return ResourceManager.GetString("CapacityDetails_DoesPatientHaveASoundedMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the balance of probabilities, based on the evidence above, does the patient HAVE the capacity to make this particular decision at this moment in time?.
        /// </summary>
        public static string CapacityDetails_DoesPatientLackCapacityToDecide {
            get {
                return ResourceManager.GetString("CapacityDetails_DoesPatientLackCapacityToDecide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the patient able to understand the information relating to the decision to be made?.
        /// </summary>
        public static string CapacityDetails_DoesPatientUnderstandInformationProvided {
            get {
                return ResourceManager.GetString("CapacityDetails_DoesPatientUnderstandInformationProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string CapacityDetails_Header {
            get {
                return ResourceManager.GetString("CapacityDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the capacity loss likely to be PERMANENT?.
        /// </summary>
        public static string CapacityDetails_IsLackOfCapacityPermanent {
            get {
                return ResourceManager.GetString("CapacityDetails_IsLackOfCapacityPermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the patient able to communicate their decision, by any means possible, if necessary with the help of speech and language therapists?.
        /// </summary>
        public static string CapacityDetails_IsPatientAbleToCommunicateDecision {
            get {
                return ResourceManager.GetString("CapacityDetails_IsPatientAbleToCommunicateDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the patient able to retain the information relating to the decision to be made?.
        /// </summary>
        public static string CapacityDetails_IsPatientAbleToRetainInformationProvided {
            get {
                return ResourceManager.GetString("CapacityDetails_IsPatientAbleToRetainInformationProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the patient able to use the information to enable them to make an informed decision?.
        /// </summary>
        public static string CapacityDetails_IsPatientAbleToUseInfromationProvided {
            get {
                return ResourceManager.GetString("CapacityDetails_IsPatientAbleToUseInfromationProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the patient UNCONSCIOUS?.
        /// </summary>
        public static string CapacityDetails_IsPatientUnconscious {
            get {
                return ResourceManager.GetString("CapacityDetails_IsPatientUnconscious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the details of support provided to the patient to enable them to make the decision themselves.
        /// </summary>
        public static string CapacityDetails_SupportProvided {
            get {
                return ResourceManager.GetString("CapacityDetails_SupportProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the patient has capacity to make this decision at this time.
        /// </summary>
        public static string CapacityTest_Description {
            get {
                return ResourceManager.GetString("CapacityTest_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity Test.
        /// </summary>
        public static string CapacityTest_Header {
            get {
                return ResourceManager.GetString("CapacityTest_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPACITY TEST.
        /// </summary>
        public static string CapacityTest_Title {
            get {
                return ResourceManager.GetString("CapacityTest_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the patient ever been officially informed that they are at an increased risk of CJD or vCJD.
        /// </summary>
        public static string CJDRiskAssessment_Item1 {
            get {
                return ResourceManager.GetString("CJDRiskAssessment_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If YES, has a formal risk assessment been carried out.
        /// </summary>
        public static string CJDRiskAssessment_Item2 {
            get {
                return ResourceManager.GetString("CJDRiskAssessment_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJD Risk Assessment.
        /// </summary>
        public static string CJDRiskAssessment_Title {
            get {
                return ResourceManager.GetString("CJDRiskAssessment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Alternative Procedures.
        /// </summary>
        public static string Common_AddAlternativeProcedures {
            get {
                return ResourceManager.GetString("Common_AddAlternativeProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Procedures.
        /// </summary>
        public static string Common_AddProcedures {
            get {
                return ResourceManager.GetString("Common_AddProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits: .
        /// </summary>
        public static string Common_Benefits {
            get {
                return ResourceManager.GetString("Common_Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Transfusion Consent.
        /// </summary>
        public static string Common_BloodTranfusionConsent {
            get {
                return ResourceManager.GetString("Common_BloodTranfusionConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent Health Professional.
        /// </summary>
        public static string Common_ConsentHealthProfessional {
            get {
                return ResourceManager.GetString("Common_ConsentHealthProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string Common_ContactNumber {
            get {
                return ResourceManager.GetString("Common_ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Common_Date {
            get {
                return ResourceManager.GetString("Common_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Maker.
        /// </summary>
        public static string Common_DecisionMaker {
            get {
                return ResourceManager.GetString("Common_DecisionMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Common_Details {
            get {
                return ResourceManager.GetString("Common_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string Common_DOB {
            get {
                return ResourceManager.GetString("Common_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINISH.
        /// </summary>
        public static string Common_Finish {
            get {
                return ResourceManager.GetString("Common_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Common_FirstName {
            get {
                return ResourceManager.GetString("Common_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Post-operative/Follow-up Cares: .
        /// </summary>
        public static string Common_Followup {
            get {
                return ResourceManager.GetString("Common_Followup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent/Assent.
        /// </summary>
        public static string Common_GeneralConsent {
            get {
                return ResourceManager.GetString("Common_GeneralConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Professional.
        /// </summary>
        public static string Common_HealthProfessional {
            get {
                return ResourceManager.GetString("Common_HealthProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Professional Signature.
        /// </summary>
        public static string Common_HealthProfessionalSignature {
            get {
                return ResourceManager.GetString("Common_HealthProfessionalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreter.
        /// </summary>
        public static string Common_Interpreter {
            get {
                return ResourceManager.GetString("Common_Interpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the interpreter&apos;s full name.
        /// </summary>
        public static string Common_InterpreterFullName {
            get {
                return ResourceManager.GetString("Common_InterpreterFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string Common_JobTitle {
            get {
                return ResourceManager.GetString("Common_JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        public static string Common_Menu {
            get {
                return ResourceManager.GetString("Common_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEXT.
        /// </summary>
        public static string Common_Next {
            get {
                return ResourceManager.GetString("Common_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number.
        /// </summary>
        public static string Common_NHSNumber {
            get {
                return ResourceManager.GetString("Common_NHSNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Stage Consent.
        /// </summary>
        public static string Common_OneStageConsent {
            get {
                return ResourceManager.GetString("Common_OneStageConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organ Donation Consent.
        /// </summary>
        public static string Common_OrganDonationConsent {
            get {
                return ResourceManager.GetString("Common_OrganDonationConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent&apos;s/Representative&apos;s Name.
        /// </summary>
        public static string Common_ParentOrRepresentativeName {
            get {
                return ResourceManager.GetString("Common_ParentOrRepresentativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient&apos;s Name.
        /// </summary>
        public static string Common_PatientName {
            get {
                return ResourceManager.GetString("Common_PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient&apos;s/Representative&apos;s Name.
        /// </summary>
        public static string Common_PatientOrRepresentativeName {
            get {
                return ResourceManager.GetString("Common_PatientOrRepresentativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient&apos;s/Representative&apos;s Signature.
        /// </summary>
        public static string Common_PatientOrRepresentativeSignature {
            get {
                return ResourceManager.GetString("Common_PatientOrRepresentativeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient&apos;s Signature.
        /// </summary>
        public static string Common_PatientSignature {
            get {
                return ResourceManager.GetString("Common_PatientSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographic Consent.
        /// </summary>
        public static string Common_PhotograpicConsent {
            get {
                return ResourceManager.GetString("Common_PhotograpicConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Morten Consent.
        /// </summary>
        public static string Common_PostMortemConsent {
            get {
                return ResourceManager.GetString("Common_PostMortemConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Name.
        /// </summary>
        public static string Common_ProcedureName {
            get {
                return ResourceManager.GetString("Common_ProcedureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Name.
        /// </summary>
        public static string Common_Procedures {
            get {
                return ResourceManager.GetString("Common_Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship to the patient.
        /// </summary>
        public static string Common_Relationship {
            get {
                return ResourceManager.GetString("Common_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Health Professional.
        /// </summary>
        public static string Common_ResponsibleHealthProfessional {
            get {
                return ResourceManager.GetString("Common_ResponsibleHealthProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risks: .
        /// </summary>
        public static string Common_Risks {
            get {
                return ResourceManager.GetString("Common_Risks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role/Relationship.
        /// </summary>
        public static string Common_RoleOrRelationship {
            get {
                return ResourceManager.GetString("Common_RoleOrRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Common_Signature {
            get {
                return ResourceManager.GetString("Common_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed.
        /// </summary>
        public static string Common_Signed {
            get {
                return ResourceManager.GetString("Common_Signed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Requirements.
        /// </summary>
        public static string Common_SpecialRequirements {
            get {
                return ResourceManager.GetString("Common_SpecialRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Common_Surname {
            get {
                return ResourceManager.GetString("Common_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness&apos;s Name.
        /// </summary>
        public static string Common_WitnessName {
            get {
                return ResourceManager.GetString("Common_WitnessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose appropriate consent stage from the following options.
        /// </summary>
        public static string ConsentStage_Description {
            get {
                return ResourceManager.GetString("ConsentStage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent Stage.
        /// </summary>
        public static string ConsentStage_Header {
            get {
                return ResourceManager.GetString("ConsentStage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Stage.
        /// </summary>
        public static string ConsentStage_StageEmergency {
            get {
                return ResourceManager.GetString("ConsentStage_StageEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Stage.
        /// </summary>
        public static string ConsentStage_StageNormal {
            get {
                return ResourceManager.GetString("ConsentStage_StageNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration.
        /// </summary>
        public static string DeclarationDetails_Header {
            get {
                return ResourceManager.GetString("DeclarationDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation of consent (to be completed by the patient and a health professional after the First Stage has been completed and within 72 hours of the procedure.). On behalf of the team treating the patient, the health professional has confirmed with the patient that he/she has no further questions and wishes the procedure to go ahead..
        /// </summary>
        public static string FinalConsent_ConsentInformation {
            get {
                return ResourceManager.GetString("FinalConsent_ConsentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Consent.
        /// </summary>
        public static string FinalConsent_Header {
            get {
                return ResourceManager.GetString("FinalConsent_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINAL STAGE CONSENT.
        /// </summary>
        public static string FinalConsent_Title {
            get {
                return ResourceManager.GetString("FinalConsent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Consent.
        /// </summary>
        public static string FirstConsent_Header {
            get {
                return ResourceManager.GetString("FirstConsent_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRST STAGE CONSENT.
        /// </summary>
        public static string FirstConsent_Title {
            get {
                return ResourceManager.GetString("FirstConsent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read this form carefully. If the patient&apos;s treatment is being planned in advance, patient may be given a patient information leaflet about the procedure. If the patient has any further questions, please ask the responsible health professional(s) immediately..
        /// </summary>
        public static string FirstStageConsentAdult_Paragraph1 {
            get {
                return ResourceManager.GetString("FirstStageConsentAdult_Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient has the right to change his/her mind at any time, including after signature is captured at this stage..
        /// </summary>
        public static string FirstStageConsentAdult_Paragraph2 {
            get {
                return ResourceManager.GetString("FirstStageConsentAdult_Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient understands that health professionals cannot give him/her a guarantee that a particular person will perform the procedure. The person will, however, have appropriate experience and training..
        /// </summary>
        public static string FirstStageConsentAdult_Paragraph3 {
            get {
                return ResourceManager.GetString("FirstStageConsentAdult_Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient understands that he/she will have the opportunity to discuss the details of anaesthesia with an anaesthetist before the procedure, unless the urgency of situation prevents this. (This only applies to patients having general or regional anaesthesia)..
        /// </summary>
        public static string FirstStageConsentAdult_Paragraph4 {
            get {
                return ResourceManager.GetString("FirstStageConsentAdult_Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient understands that any procedures in addition to those described on this form will only be carried out if it is necessary to save his/her life or to prevent serous harm to his/her health..
        /// </summary>
        public static string FirstStageConsentAdult_Paragraph5 {
            get {
                return ResourceManager.GetString("FirstStageConsentAdult_Paragraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient has been told about additional procedures which may become necessary during his/her treatment. The patient has listed below any procedures which he/she do not wish to be carried out without further discussion..
        /// </summary>
        public static string FirstStageConsentAdult_Paragraph6 {
            get {
                return ResourceManager.GetString("FirstStageConsentAdult_Paragraph6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement of ADULT patient and young people aged 16 years and above..
        /// </summary>
        public static string FirstStageConsentAdult_Subtitle1 {
            get {
                return ResourceManager.GetString("FirstStageConsentAdult_Subtitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A young person under the age of 16 years may sign here if they have been shown to have capacity..
        /// </summary>
        public static string FirstStageConsentAdult_Subtitle2 {
            get {
                return ResourceManager.GetString("FirstStageConsentAdult_Subtitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read this form carefully. If your treatment is being planned in advance, you may be given a patient information leaflet about the procedure. If you have any further questions, you must ask - we are here to help you..
        /// </summary>
        public static string FirstStageConsentProxy_Paragraph1 {
            get {
                return ResourceManager.GetString("FirstStageConsentProxy_Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent/representative has the right to change his/her mind at any time, including after signature is captured at this stage..
        /// </summary>
        public static string FirstStageConsentProxy_Paragraph2 {
            get {
                return ResourceManager.GetString("FirstStageConsentProxy_Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent/representative agrees to the procedure or course of treatment described on this form..
        /// </summary>
        public static string FirstStageConsentProxy_Paragraph3 {
            get {
                return ResourceManager.GetString("FirstStageConsentProxy_Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent/representative understands that the health professionals cannot give a guarantee that a particular person will perform the procedure. the person will, however, have appropriate experience and training..
        /// </summary>
        public static string FirstStageConsentProxy_Paragraph4 {
            get {
                return ResourceManager.GetString("FirstStageConsentProxy_Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent/representative understands that his/her child/client and himself/herself will have the opportunity to discuss the details of anaesthesia with an anaesthetist before the procedure, unless the urgency of the situation prevents this. (This only applies to children having general or regional anaesthesia)..
        /// </summary>
        public static string FirstStageConsentProxy_Paragraph5 {
            get {
                return ResourceManager.GetString("FirstStageConsentProxy_Paragraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent/representative understands that any procedures in addition to those described on this form will only be carried out if it is necessary to save the life of his/her child/client or to prevent serous harm to his or her health..
        /// </summary>
        public static string FirstStageConsentProxy_Paragraph6 {
            get {
                return ResourceManager.GetString("FirstStageConsentProxy_Paragraph6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parent/representative has been told about additional procedures which may become necessary during his/her child/client&apos;s treatment. The parent/representative has listed below any procedures which he/she do not wish to be carried out without further discussion..
        /// </summary>
        public static string FirstStageConsentProxy_Paragraph7 {
            get {
                return ResourceManager.GetString("FirstStageConsentProxy_Paragraph7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement of parent or legal proxy for a CHILD under 16 years old and not legally competent.
        /// </summary>
        public static string FirstStageConsentProxy_Subtitle {
            get {
                return ResourceManager.GetString("FirstStageConsentProxy_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE POST-OPERATIVE/FOLLOW-UP CARE.
        /// </summary>
        public static string FollowsSelected_Title {
            get {
                return ResourceManager.GetString("FollowsSelected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Care Professional Declaration.
        /// </summary>
        public static string HealthCareProfessionalDeclaration_Title {
            get {
                return ResourceManager.GetString("HealthCareProfessionalDeclaration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEALTH PROFESSIONAL DETAILS.
        /// </summary>
        public static string HealthProfessionalDetails_Title {
            get {
                return ResourceManager.GetString("HealthProfessionalDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreter Details.
        /// </summary>
        public static string InterpreterDetails_Header {
            get {
                return ResourceManager.GetString("InterpreterDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the interpreter present?.
        /// </summary>
        public static string InterpreterDetails_Present {
            get {
                return ResourceManager.GetString("InterpreterDetails_Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have interpreted the information to the patient to the best of my ability and in a way in which I believe the patient can understand..
        /// </summary>
        public static string InterpreterSignature_Declaration {
            get {
                return ResourceManager.GetString("InterpreterSignature_Declaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpreter.
        /// </summary>
        public static string InterpreterSignature_Header {
            get {
                return ResourceManager.GetString("InterpreterSignature_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERPRETER SIGNATURE.
        /// </summary>
        public static string InterpreterSignature_Title {
            get {
                return ResourceManager.GetString("InterpreterSignature_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm patient understands English language.
        /// </summary>
        public static string LanguageAssessment_Description {
            get {
                return ResourceManager.GetString("LanguageAssessment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Assessment.
        /// </summary>
        public static string LanguageAssessment_Header {
            get {
                return ResourceManager.GetString("LanguageAssessment_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Patient Consent System.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient/parent agrees that in the interests of training competent health care professionals for the future students may be allowed to observe the patient&apos;s/child&apos;s operation.
        /// </summary>
        public static string MedicalStudents_Agreement1 {
            get {
                return ResourceManager.GetString("MedicalStudents_Agreement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient/parents agrees that in the interests of education, medical students may be allowed to contribute to the patient&apos;s/child&apos;s operation on the understanding that their contribution is fully supervised and within their current experience and competence.
        /// </summary>
        public static string MedicalStudents_Agreement2 {
            get {
                return ResourceManager.GetString("MedicalStudents_Agreement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient/parent agrees to photography and/or videos taken during the procedure for the purpose of adding dinical information to my medical notes. Additional consent is required for these images to be used for any other purpose.
        /// </summary>
        public static string MedicalStudents_Agreement3 {
            get {
                return ResourceManager.GetString("MedicalStudents_Agreement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVOLVEMENT OF MEDICAL/NURSING STUDENTS AND PHOTOGRAPHY/FILMING.
        /// </summary>
        public static string MedicalStudents_Title {
            get {
                return ResourceManager.GetString("MedicalStudents_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demographic.
        /// </summary>
        public static string PatientDetails_Header {
            get {
                return ResourceManager.GetString("PatientDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Details.
        /// </summary>
        public static string PatientDetails_Title {
            get {
                return ResourceManager.GetString("PatientDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures.
        /// </summary>
        public static string ProcedureDetails_Header {
            get {
                return ResourceManager.GetString("ProcedureDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Search.
        /// </summary>
        public static string ProcedureList_Header {
            get {
                return ResourceManager.GetString("ProcedureList_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCEDURES PROPOSED.
        /// </summary>
        public static string ProceduresSelected_Title {
            get {
                return ResourceManager.GetString("ProceduresSelected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you are trained to take consent for this procedure or qualified to perform the procedure?.
        /// </summary>
        public static string Qualification_Description {
            get {
                return ResourceManager.GetString("Qualification_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you qualified to take Consent?.
        /// </summary>
        public static string Qualification_Header {
            get {
                return ResourceManager.GetString("Qualification_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use letters (a-z) and space only.
        /// </summary>
        public static string ValidationMessage_LettersAndSpaceValidation {
            get {
                return ResourceManager.GetString("ValidationMessage_LettersAndSpaceValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field can not be empty.
        /// </summary>
        public static string ValidationMessage_RequiredField {
            get {
                return ResourceManager.GetString("ValidationMessage_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact number must be in a valid format, i.e, +44 0203 299 9000.
        /// </summary>
        public static string ValidationMessage_TelephoneNumberValidation {
            get {
                return ResourceManager.GetString("ValidationMessage_TelephoneNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the details here if other anaesthesia is required.
        /// </summary>
        public static string Watermark_AnaesthesiaOther {
            get {
                return ResourceManager.GetString("Watermark_AnaesthesiaOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the details of decision made, on the basis of all the facts and views expressed.
        /// </summary>
        public static string Watermark_AssentFinalDecision {
            get {
                return ResourceManager.GetString("Watermark_AssentFinalDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter benefits of the procedure.
        /// </summary>
        public static string Watermark_Benefits {
            get {
                return ResourceManager.GetString("Watermark_Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter comments here (if applicable).
        /// </summary>
        public static string Watermark_Comment {
            get {
                return ResourceManager.GetString("Watermark_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Watermark_Contact {
            get {
                return ResourceManager.GetString("Watermark_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the date.
        /// </summary>
        public static string Watermark_Date {
            get {
                return ResourceManager.GetString("Watermark_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the decision maker&apos;s full name.
        /// </summary>
        public static string Watermark_DecisionMakerFullName {
            get {
                return ResourceManager.GetString("Watermark_DecisionMakerFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the decision maker&apos;s job title.
        /// </summary>
        public static string Watermark_DecisionMakerJobTitle {
            get {
                return ResourceManager.GetString("Watermark_DecisionMakerJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter description for your procedure.
        /// </summary>
        public static string Watermark_Description {
            get {
                return ResourceManager.GetString("Watermark_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide evidence for your answer.
        /// </summary>
        public static string Watermark_Evidence {
            get {
                return ResourceManager.GetString("Watermark_Evidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter follow-up cares of the procedure.
        /// </summary>
        public static string Watermark_FollowupCare {
            get {
                return ResourceManager.GetString("Watermark_FollowupCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Watermark_FullName {
            get {
                return ResourceManager.GetString("Watermark_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the health professional&apos;s contact number (if applicable).
        /// </summary>
        public static string Watermark_HealthProfessionalContactNumber {
            get {
                return ResourceManager.GetString("Watermark_HealthProfessionalContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the health professional&apos;s first name.
        /// </summary>
        public static string Watermark_HealthProfessionalFirstName {
            get {
                return ResourceManager.GetString("Watermark_HealthProfessionalFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the health professional&apos;s full name.
        /// </summary>
        public static string Watermark_HealthProfessionalFullName {
            get {
                return ResourceManager.GetString("Watermark_HealthProfessionalFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the health professional&apos;s job title.
        /// </summary>
        public static string Watermark_HealthProfessionalJobTitle {
            get {
                return ResourceManager.GetString("Watermark_HealthProfessionalJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please SIGN here (health professional).
        /// </summary>
        public static string Watermark_HealthProfessionalSignature {
            get {
                return ResourceManager.GetString("Watermark_HealthProfessionalSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the health professional&apos;s surname.
        /// </summary>
        public static string Watermark_HealthProfessionalSurname {
            get {
                return ResourceManager.GetString("Watermark_HealthProfessionalSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the interpreter&apos;s full name.
        /// </summary>
        public static string Watermark_InterpreterFullName {
            get {
                return ResourceManager.GetString("Watermark_InterpreterFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please SIGN here (interpreter).
        /// </summary>
        public static string Watermark_InterpreterSignature {
            get {
                return ResourceManager.GetString("Watermark_InterpreterSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the reason for a Capacity Assessment, i.e., behaviour, circumstances, concerns, medical diagnosis and etc.?.
        /// </summary>
        public static string Watermark_IsPatientConscious {
            get {
                return ResourceManager.GetString("Watermark_IsPatientConscious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the parent or representative&apos;s full name.
        /// </summary>
        public static string Watermark_ParentOrRepresentativeFullName {
            get {
                return ResourceManager.GetString("Watermark_ParentOrRepresentativeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please SIGN here (parent or representative).
        /// </summary>
        public static string Watermark_ParentOrRepresentativeSignature {
            get {
                return ResourceManager.GetString("Watermark_ParentOrRepresentativeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the patient&apos;s date of birth.
        /// </summary>
        public static string Watermark_PatientDOB {
            get {
                return ResourceManager.GetString("Watermark_PatientDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the patient&apos;s first name.
        /// </summary>
        public static string Watermark_PatientFirstName {
            get {
                return ResourceManager.GetString("Watermark_PatientFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the patient&apos;s full name.
        /// </summary>
        public static string Watermark_PatientFullName {
            get {
                return ResourceManager.GetString("Watermark_PatientFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter patient&apos;s NHS number.
        /// </summary>
        public static string Watermark_PatientNHSNumber {
            get {
                return ResourceManager.GetString("Watermark_PatientNHSNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the patient or representative&apos;s full name.
        /// </summary>
        public static string Watermark_PatientOrRepresentativeFullName {
            get {
                return ResourceManager.GetString("Watermark_PatientOrRepresentativeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please SIGN here (patient or representative).
        /// </summary>
        public static string Watermark_PatientOrRepresentativeSignature {
            get {
                return ResourceManager.GetString("Watermark_PatientOrRepresentativeSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please SIGN here (patient).
        /// </summary>
        public static string Watermark_PatientSignature {
            get {
                return ResourceManager.GetString("Watermark_PatientSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter patient&apos;s special requirements (if applicable).
        /// </summary>
        public static string Watermark_PatientSpecialRequirements {
            get {
                return ResourceManager.GetString("Watermark_PatientSpecialRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the patient&apos;s surname.
        /// </summary>
        public static string Watermark_PatientSurname {
            get {
                return ResourceManager.GetString("Watermark_PatientSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the person&apos;s first name.
        /// </summary>
        public static string Watermark_PersonFirstName {
            get {
                return ResourceManager.GetString("Watermark_PersonFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the person&apos;s job title.
        /// </summary>
        public static string Watermark_PersonJobTitle {
            get {
                return ResourceManager.GetString("Watermark_PersonJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the person&apos;s role or relationship.
        /// </summary>
        public static string Watermark_PersonRoleOrRelationship {
            get {
                return ResourceManager.GetString("Watermark_PersonRoleOrRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the person&apos;s surname.
        /// </summary>
        public static string Watermark_PersonSurname {
            get {
                return ResourceManager.GetString("Watermark_PersonSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the procedure.
        /// </summary>
        public static string Watermark_Procedures {
            get {
                return ResourceManager.GetString("Watermark_Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string Watermark_Relationship {
            get {
                return ResourceManager.GetString("Watermark_Relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter risks of the procedure.
        /// </summary>
        public static string Watermark_Risks {
            get {
                return ResourceManager.GetString("Watermark_Risks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Procedure.
        /// </summary>
        public static string Watermark_SearchProcedure {
            get {
                return ResourceManager.GetString("Watermark_SearchProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attends with someone who knows them well
        ///Enough time allowed
        ///Best time of the day
        ///Using communication methods that the patient understands.
        /// </summary>
        public static string Watermark_SupportProvided {
            get {
                return ResourceManager.GetString("Watermark_SupportProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Watermark_View {
            get {
                return ResourceManager.GetString("Watermark_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the witness&apos;s full name.
        /// </summary>
        public static string Watermark_WitnessFullName {
            get {
                return ResourceManager.GetString("Watermark_WitnessFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please SIGN here (witness).
        /// </summary>
        public static string Watermark_WitnessSignature {
            get {
                return ResourceManager.GetString("Watermark_WitnessSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witness.
        /// </summary>
        public static string Witness_Header {
            get {
                return ResourceManager.GetString("Witness_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERPRETER (where appropriate): I have interpreted the information above to the patient to the best of my ability and in a way in which I believe the patient can understand..
        /// </summary>
        public static string Witness_InterpreterInfo {
            get {
                return ResourceManager.GetString("Witness_InterpreterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITNESS.
        /// </summary>
        public static string Witness_Title {
            get {
                return ResourceManager.GetString("Witness_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A witness should sign below if the patient is unable to sign but has indicated his or her consent..
        /// </summary>
        public static string Witness_WitnessInformation1 {
            get {
                return ResourceManager.GetString("Witness_WitnessInformation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Young people aged 16 or 17 years old and children with capacity may also like a parent to sign here..
        /// </summary>
        public static string Witness_WitnessInformation2 {
            get {
                return ResourceManager.GetString("Witness_WitnessInformation2", resourceCulture);
            }
        }
    }
}
